export enum EMicroservice {
  SSO_SERVICE = 'SSO_SERVICE',
  BOOKING_SERVICE = 'BOOKING_SERVICE',

  // aggregation
  AGGREGATION_SSO_SERVICE = 'AGGREGATION_SSO_SERVICE',
  AGGREGATION_BOOKING_SERVICE = 'AGGREGATION_BOOKING_SERVICE',

  // guard
  AUTHENTICATION_GUARD = 'AUTHENTICATION_GUARD',
}

export enum EKafkaGroup {
  SSO_GROUP = 'SSO_GROUP',
  AGGREGATION_GROUP = 'AGGREGATION_GROUP',
  BOOKING_GROUP = 'BOOKING_GROUP',
  AUTHENTICATION_GUARD_GROUP = 'AUTHENTICATION_GUARD_GROUP',
}

export enum EKafkaMessage {
  REQUEST_LOGIN = 'REQUEST_LOGIN',
  REQUEST_CREATE_USER = 'REQUEST_CREATE_USER',
  REQUEST_VERIFY_TOKEN = 'REQUEST_VERIFY_TOKEN',
  REQUEST_EXCEPTION_TEST = 'REQUEST_EXCEPTION_TEST',

  REQUEST_FIND_AVAILABLE_ROOMS = 'REQUEST_FIND_AVAILABLE_ROOMS',
  REQUEST_BOOK_ROOMS = 'REQUEST_BOOK_ROOMS',
}
